### ISSUE TITLE
按readme添加了依赖之后，仍然无法找到某些依赖的类

### ISSUE THREAD

**Issue by RomoteDY** [AgoraIO-Usecase/Chatroom#15]
下载的sdk是Androidv2.9.2

**Comment by plutoless** [comment]
麻烦把错误信息发一下

**Comment by RomoteDY** [comment]
import io.agora.rtm.ChannelAttributeOptions;
import io.agora.rtm.ErrorInfo;
import io.agora.rtm.ResultCallback;
import io.agora.rtm.RtmAttribute;
import io.agora.rtm.RtmChannel;
import io.agora.rtm.RtmChannelAttribute;
import io.agora.rtm.RtmChannelListener;
import io.agora.rtm.RtmChannelMember;
import io.agora.rtm.RtmClient;
import io.agora.rtm.RtmClientListener;
import io.agora.rtm.RtmMessage;
随便拿RtmManager 来说，上面的类都找不到报红，在AS里查看agora-rtc-sdk.jar的包结构，发现没有rtm这个包，io.agora下面有两个包一个是live另一个是rtc，找不到rtm包

**Comment by plutoless** [comment]
rtm是另外的sdk

**Comment by RomoteDY** [comment]
谢谢，我没仔细看截图

**Comment by RomoteDY** [comment]
谢谢，我没仔细看截图
