### ISSUE TITLE
swift代码中引入的AgoraAudioKit这个sdk在哪里下载

### ISSUE THREAD

**Issue by SuiTangGuCheng** [AgoraIO-Usecase/Chatroom#16]

**Comment by LichKing-2234** [comment]
readme中有写在哪里下载sdk的

**Comment by SuiTangGuCheng** [comment]
> readme

我下载的是v3.0.0版本没有这个sdk了。readme中用的v2.9.1版本。现在v2.9.1版本在哪里下载

**Comment by LichKing-2234** [comment]
https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v2_9_1_VOICE.zip

**Comment by plutoless** [comment]
我们会在近期适配3.0版本

**Comment by LichKing-2234** [comment]
@SuiTangGuCheng 现在demo已经适配3.0.0版本SDK

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
