### ISSUE TITLE
第二次进入房间上麦会闪烁

### ISSUE THREAD

**Issue by wkxqasim** [AgoraIO-Usecase/Chatroom#17]
作为观众进入房间后，上麦，退出房间，再进入房间，上其他麦，会在前一次上麦的位置闪烁一下。

**Comment by LichKing-2234** [comment]
感谢提出问题，目前已经修复，再尝试下

**Comment by wkxqasim** [comment]
这样改只是自己看上去没问题，在别人那看还是一样啊。难道不应该是离开房间时应该先从麦位下来？

**Comment by LichKing-2234** [comment]
demo基于RTM实现，正常退出房间如果清除麦位数据是没问题的，但如果被程序被杀死，这个时候还是会有问题。最好基于业务后台实现

**Comment by LichKing-2234** [comment]
简单实现，可以在leaveChannel之前先清除相关麦位的channelAttribute

**Comment by wkxqasim** [comment]
好的
